/**
 * Single source of the icon components used on the landing page.
 *
 * Every icon is imported by name — never `import *` — so the bundler pulls in
 * only these ~30 glyphs instead of lucide's full set, and the key below is the
 * one place a name is spelled out. Components take a `name` instead of an icon
 * so template call sites stay `ICONS.foo` rather than `(LucideIcons as any)[…]`.
 */
import {
  Activity,
  AlarmClock,
  AppWindow,
  ArrowUpRight,
  Barcode,
  Bell,
  BookOpen,
  Boxes,
  CircleQuestionMark,
  ClipboardList,
  Cloud,
  Code,
  Coins,
  Copy,
  Cookie,
  Database,
  Download,
  ExternalLink,
  Gauge,
  HardDrive,
  Image,
  KeyRound,
  Languages,
  Layers,
  LifeBuoy,
  Link,
  ListChecks,
  ListOrdered,
  MessageCircle,
  MonitorSmartphone,
  MousePointerClick,
  Package,
  PackageSearch,
  Palette,
  Receipt,
  Rocket,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  SquareMenu,
  Store,
  Table,
  Wifi,
  Zap,
} from '@lucide/vue';

export const ICONS = {
  account: KeyRound,
  activeTab: MousePointerClick,
  alarms: Zap,
  analytics: Search,
  appWindow: AppWindow,
  assistant: Sparkles,
  barcode: Barcode,
  batches: Package,
  browse: Search,
  browsingHistory: Cookie,
  category: Layers,
  cloudPool: Cloud,
  contextMenus: SquareMenu,
  cta: Download,
  dataStore: Database,
  design: Palette,
  docs: BookOpen,
  duplicate: Copy,
  engine: Gauge,
  export: Table,
  external: ExternalLink,
  faq: CircleQuestionMark,
  footerLink: ArrowUpRight,
  image: Image,
  keyRound: KeyRound,
  link: Link,
  list: ClipboardList,
  multiAccount: Store,
  notifications: Bell,
  overview: Activity,
  password: KeyRound,
  permAlarms: AlarmClock,
  permNotifications: Bell,
  permScripting: Zap,
  permStorage: HardDrive,
  pipeline: Rocket,
  price: Coins,
  privacy: ShieldCheck,
  productDetails: ShoppingBag,
  productImages: Image,
  scripting: Code,
  serial: ListOrdered,
  settings: Settings,
  sources: PackageSearch,
  status: Wifi,
  storeSetup: Store,
  support: LifeBuoy,
  sync: MonitorSmartphone,
  tasks: ListChecks,
  terms: ScrollText,
  translate: Languages,
  variants: Boxes,
  vat: Receipt,
  wechat: MessageCircle,
  zap: Zap,
} as const;

export type IconKey = keyof typeof ICONS;
